/* eslint-disable @next/next/no-img-element */
import React from 'react'

const posts = [
  {
    imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/adidas.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/agusti-torello-mata.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/alfaparf.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/audi.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/bacardi.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/carrefour.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/cebado.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/cinesa.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/ciruit-catalunya.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/clarion.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/Danone.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/dulcesol.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/elpozo.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/farina.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/ferrari.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/freeman.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/freixenet.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/GinMG.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/isabel.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/jamon-teruel.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/kellogs.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/lakme.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/llongueras.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/loreal.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/lucky.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/mango.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/marco_aldany.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/massimo.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/me-by-melia.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/melia.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/mercedes.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/mga-grupo.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/montibello.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/nal3comunicacio.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/noel.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/norma.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/oleoestepa.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/onecowork.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/oysho.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/parc-valles.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/PhilipMorris.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/porsche-300x188.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/porsche.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/privalia.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/rally-car.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/revlon.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/sasson.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/schwarkopf.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/seat.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/seatra.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/sorisa.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/suzuki.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/telefonica.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/thuya.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/tony-guy.png?raw=true',
  },
  {
  imageUrl:
    'https://github.com/sushi-js/sushis-demo/blob/main/src/common/components/elements/02%20Body/11%20CaseStudies/Case-Study-Clientes/Brands/vice.png?raw=true',
},

]

